import {
  COLLECTION_FURNITURE_MAX_SIZE,
  COLLECTION_MAX_FURNITURE,
} from "@oh/core";

export const COLLECTION_FILE_URL_EXPIRY_SECONDS = 120;

export const COLLECTION_METADATA_FILE = "collection.yml";
export const COLLECTION_METADATA_MAX_SIZE = 64 * 1024;

export const COLLECTION_FILE_MAX_UNCOMPRESSED_SIZE =
  COLLECTION_MAX_FURNITURE * COLLECTION_FURNITURE_MAX_SIZE +
  COLLECTION_METADATA_MAX_SIZE;
